name: Update Checksum

on:
  push:
    paths:
      - 'asf.sh'

jobs:
  update-checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Calculate Checksums
        run: |
          sha1=$(sha1sum asf.sh | awk '{print $1}')
          sha256=$(sha256sum asf.sh | awk '{print $1}')
          sha512=$(sha512sum asf.sh | awk '{print $1}')
          md5=$(md5sum asf.sh | awk '{print $1}')
          
          echo "MD5: $md5" >> README.md
          echo "SHA1: $sha1" >> README.md
          echo "SHA256: $sha256" >> README.md
          echo "SHA512: $sha512" >> README.md
      - name: Commit Changes
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: main
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          COMMIT_MESSAGE: "Update checksums for asf.sh"
